<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<WarningsAsErrors></WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>