// <auto-generated />
using System;
using ChaloJi.Modules.Auth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChaloJi.Modules.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260525072435_driverprofile")]
    partial class driverprofile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.AadhaarKyc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AadhaarBackImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("AadhaarFrontImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOtpVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId")
                        .IsUnique();

                    b.ToTable("AadhaarKycs");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.DriverLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("text");

                    b.Property<string>("LicenseBackImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LicenseClass")
                        .HasColumnType("text");

                    b.Property<string>("LicenseFrontImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId")
                        .IsUnique();

                    b.ToTable("DriverLicenses");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.DriverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("KycStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LivePhotoCapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LivePhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DriverProfiles");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.PanCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("NameOnPan")
                        .HasColumnType("text");

                    b.Property<string>("PanImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId")
                        .IsUnique();

                    b.ToTable("PanCards");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.VehicleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FitnessCertificateNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FitnessExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FitnessImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceCompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsuranceExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsuranceImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InsurancePolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PermitExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermitImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RcExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RcImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("RcNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleColor")
                        .HasColumnType("text");

                    b.Property<string>("VehicleFrontImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("text");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleSideImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId")
                        .IsUnique();

                    b.ToTable("VehicleDetails");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.AadhaarKyc", b =>
                {
                    b.HasOne("ChaloJi.Modules.Auth.Models.DriverProfile", "DriverProfile")
                        .WithOne("AadhaarKyc")
                        .HasForeignKey("ChaloJi.Modules.Auth.Models.AadhaarKyc", "DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.DriverLicense", b =>
                {
                    b.HasOne("ChaloJi.Modules.Auth.Models.DriverProfile", "DriverProfile")
                        .WithOne("DriverLicense")
                        .HasForeignKey("ChaloJi.Modules.Auth.Models.DriverLicense", "DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.DriverProfile", b =>
                {
                    b.HasOne("ChaloJi.Modules.Auth.Models.User", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("ChaloJi.Modules.Auth.Models.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.PanCard", b =>
                {
                    b.HasOne("ChaloJi.Modules.Auth.Models.DriverProfile", "DriverProfile")
                        .WithOne("PanCard")
                        .HasForeignKey("ChaloJi.Modules.Auth.Models.PanCard", "DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.VehicleDetail", b =>
                {
                    b.HasOne("ChaloJi.Modules.Auth.Models.DriverProfile", "DriverProfile")
                        .WithOne("VehicleDetail")
                        .HasForeignKey("ChaloJi.Modules.Auth.Models.VehicleDetail", "DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.DriverProfile", b =>
                {
                    b.Navigation("AadhaarKyc");

                    b.Navigation("DriverLicense");

                    b.Navigation("PanCard");

                    b.Navigation("VehicleDetail");
                });

            modelBuilder.Entity("ChaloJi.Modules.Auth.Models.User", b =>
                {
                    b.Navigation("DriverProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
